service: workout-diary
provider:
  name: aws
  stage: ${env:stage}
  region: us-east-1
 
functions:
  app:
    name: workout-diary-${env:stage}
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
    image: ${env:image}
    environment:
      DATABASE_URL: ${env:DATABASE_URL}
