service: workout-diary-api
provider:
  name: aws
  stage: ${env:STAGE}
  region: us-east-1
 
functions:
  app:
    name: workout-diary-api-${env:STAGE}
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
    image: ${env:IMAGE}
    environment:
      DATABASE_URL: ${env:DATABASE_URL}
